services:
  - type: web
    name: youtube-sentiment-fastapi
    env: python
    buildCommand: pip install -r requirements-fastapi.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FRONTEND_ORIGINS
        value: https://youtube-sentiment-25.streamlit.app/